title: 0xkursad Security Blog
email: 0xkursad@gmail.com
description: Siber Güvenlik Falan Filan
url: https://python4hackersblog.github.io
plugins:
    - jekyll-seo-tag
    - jekyll-relative-links
    - jekyll-paginate
relative_links:
    enabled: true
    collections: true
highlighter: rouge
paginate: 7
paginate_path: /page:num/
twitter:
    username: 0xkursad
    card: summary
